name: 'Wolfia iOS Build Setup'
description: 'A GitHub Action to setup the environment for building and signing iOS apps.'
author: 'Wolfia'
branding:
  icon: 'box'
  color: 'gray-dark'
inputs:
  app-store-connect-api-key-id:
    description: 'App Store Connect API Key ID'
    required: true
  app-store-connect-api-issuer:
    description: 'App Store Connect API Issuer'
    required: true
  app-store-connect-secret-base64:
    description: 'App Store Connect API private key file contents (base64 encoded)'
    required: true
  certificate-base64:
    description: 'The contents of the certificate associated with the provisioning profile used to sign the app (base64 encoded)'
    required: true
  certificate-password:
    description: 'The password for the certificate associated with the provisioning profile used to sign the app'
    required: true
  profile-name:
    description: 'The name of the provisioning profile to fetch and use'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
