name: 'Test'
on:
  push:
    branches:
      - '**'

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    environment: nightly
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Compile and build github action
        run: |
          npm ci
          npm run all
      # - name: Run action
      #   id: ios-build-setup
      #   uses: ./
      #   with:
      #     app-store-connect-api-key-id: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
      #     app-store-connect-api-issuer: ${{ secrets.APP_STORE_CONNECT_API_ISSUER }}
      #     app-store-connect-secret-base64: ${{ secrets.APP_STORE_CONNECT_SECRET_BASE64 }}
      #     profile-name: 'Profile Name'
      # - name: Output decoded profile
      #   run: |
      #     echo -n "${{ steps.ios-build-setup.outputs.provisioning-profile }}" | base64 --decode
      - name: Validate distribution
        run: npm run validate-distribution
      # TODO: enable once one version has been released.
      # - name: Validate version
      #   run: npm run validate-version
      - name: Validate formatting
        run: npm run validate-formatting
